import { Router } from '@angular/router';

import { Component, OnInit, ViewChild, Inject } from '@angular/core';
import { MatTableDataSource, MatPaginator, MatSort, MatDialog, MatDialogRef, MAT_DIALOG_DATA } from '@angular/material';
import { FormGroup, FormBuilder, FormControl } from '@angular/forms';
import { ReplaySubject, Subject, Observable } from 'rxjs';
import { SelectionModel } from '@angular/cdk/collections';
import { PartyDetailsComponent } from '../../party-details/party-details.component';

@Component({
  selector: 'app-epayment-in-custody',
  templateUrl: './epayment-in-custody.component.html',
  styleUrls: ['./epayment-in-custody.component.css']
})
export class EpaymentInCustodyComponent implements OnInit {


  selectedAll: Boolean = false;
  epaymentCustodyForm: FormGroup;
  auditornameCtrl: FormControl = new FormControl();
  billtypeCtrl: FormControl = new FormControl();
  majorheadCtrl: FormControl = new FormControl();

  ELEMENT_DATA: any[] =
    [
      {
        billNo: '156',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '554',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '551',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },

      {
        billNo: '157',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '555',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Mr. A M Joshi',
        tokenNo: '552',
        billAmount: '2540.00',
        billGrossAmount: '3574.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'No',
      },

      {
        billNo: '158',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        billGrossAmount: '3650.00',
        tokenNo: '553',
        officeName: 'Collector Office, Gandhinagar',
        billAmount: '1540.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        majorHead: '2054',
        category: 'Regular',
        exempted: 'Yes',
        regNo: '556',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Mr. ABC',
      },
      {
        billNo: '159',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '557',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '554',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '160',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '558',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '555',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '161',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '559',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '556',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '162',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '560',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '557',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '163',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '561',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '558',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '164',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '562',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '559',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '165',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '563',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '560',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '166',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '564',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '561',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '167',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '565',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '562',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '168',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '566',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '563',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '169',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '567',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '564',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '170',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '568',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '565',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '171',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '569',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '566',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '172',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '570',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '567',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '173',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '571',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '568',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '174',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '572',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '569',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '175',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '573',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '570',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '176',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '574',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '571',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '177',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '575',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '572',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '178',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '576',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '573',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '179',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '577',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '574',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '180',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '578',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '575',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '181',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '579',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '576',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '182',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '580',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '577',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '183',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '581',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '578',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '184',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '582',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '579',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '185',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '583',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '580',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '186',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '584',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '581',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '187',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '585',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '582',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '188',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '586',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '583',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '189',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '587',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '584',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '190',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '588',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '585',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '191',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '589',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '586',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '192',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '590',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '587',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '193',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '591',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '588',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '194',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '592',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '589',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '195',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '593',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '590',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '196',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '594',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '591',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '197',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '595',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '592',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '198',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '596',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '593',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '199',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '597',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '594',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '200',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '598',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '595',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '201',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '599',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '596',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '202',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '600',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '597',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '203',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '601',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '598',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '204',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '602',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '599',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '205',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '603',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '600',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '206',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '604',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '601',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '207',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '605',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '602',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '208',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '606',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '603',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '209',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '607',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '604',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '210',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '608',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '605',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '211',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '609',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '606',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '212',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '610',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '607',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '213',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '611',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '608',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '214',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '612',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '609',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '215',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '613',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '610',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '216',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '614',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '611',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '217',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '615',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '612',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '218',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '616',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '613',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '219',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '617',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '614',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '220',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '618',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '615',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '221',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '619',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '616',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '222',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '620',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '617',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '223',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '621',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '618',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '224',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '622',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '619',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '225',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '623',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '620',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '226',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '624',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '621',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '227',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '625',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '622',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '228',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '626',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '623',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '229',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '627',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '624',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '230',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '628',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '625',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '231',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '629',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '626',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '232',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '630',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '627',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '233',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '631',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '628',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '234',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '632',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '629',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '235',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '633',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '630',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '236',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '634',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '631',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '237',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '635',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '632',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '238',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '636',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '633',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '239',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '637',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '634',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '240',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '638',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '635',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '241',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '639',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '636',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '242',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '640',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '637',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '243',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '641',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '638',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '244',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '642',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '639',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '245',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '643',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '640',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '246',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '644',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '641',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '247',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '645',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '642',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '248',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '646',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '643',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '249',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '647',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '644',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '250',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '648',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '645',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '251',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '649',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '646',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '252',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '650',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '647',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '253',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '651',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '648',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '254',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '652',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '649',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '255',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '653',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '650',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '256',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '654',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '651',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '257',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '655',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '652',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '258',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '656',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '653',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '259',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '657',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '654',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '260',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '658',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '655',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '261',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '659',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '656',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '262',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '660',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '657',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '263',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '661',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '658',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '264',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '662',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '659',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '265',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '663',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '660',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '266',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '664',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '661',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '267',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '665',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '662',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '268',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '666',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '663',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '269',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '667',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '664',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '270',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '668',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '665',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '271',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '669',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '666',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '272',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '670',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '667',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '273',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '671',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '668',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '274',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '672',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '669',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '275',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '673',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '670',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '276',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '674',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '671',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '277',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '675',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '672',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '278',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '676',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '673',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '279',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '677',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '674',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '280',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '678',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '675',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '281',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '679',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '676',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '282',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '680',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '677',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '283',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '681',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '678',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '284',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '682',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '679',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '285',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '683',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '680',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '286',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '684',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '681',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '287',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '685',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '682',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '288',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '686',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '683',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '289',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '687',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '684',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '290',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '688',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '685',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '291',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '689',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '686',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '292',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '690',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '687',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '293',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '691',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '688',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '294',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '692',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '689',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '295',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '693',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '690',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '296',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '694',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '691',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '297',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '695',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '692',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '298',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '696',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '693',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '299',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '697',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '694',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '300',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '698',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '695',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '301',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '699',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '696',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '302',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '700',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '697',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '303',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '701',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '698',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '304',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '702',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '699',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '305',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '703',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '700',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '306',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '704',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '701',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '307',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '705',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '702',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },
      {
        billNo: '308',
        ePayment: 'TRY61-382932',
        ePaymentAmount: '100.00',
        regNo: '706',
        inwardDate: '25-Feb-2019',
        billDate: '01-Mar-2019',
        partyName: 'Chandreshwar Vishwanath Bhagat	',
        tokenNo: '703',
        billAmount: '100.00',
        billType: 'Pay Bill',
        ddoNo: '115',
        cardex: '4',
        billGrossAmount: '900.00',
        majorHead: '2054',
        category: 'Regular',
        officeName: 'Collector Office, Gandhinagar',
        exempted: 'Yes',
      },

    ];
  ddoname_list: any = [
    { value: '1', viewValue: '	District Treasury Office, Gandhinagar' },
  ];

  displayedColumns: string[] = ['checkBox', 'billNo', 'regNo', 'tokenNo', 'billDate',
    'inwardDate', 'ddoNo', 'cardex', 'officeName', 'billType',
    'majorHead', 'category', 'billGrossAmount', 'billAmount', 'partyName', 'ePayment',
    'ePaymentAmount', 'action'];

  auditor_list: any[] = [{
    value: '1', viewValue: 'Shri. Pratik Shah'
  },
  ];

  billtype_list: any[] = [
    { value: '1', viewValue: 'GTR-30 - Pay Bill' },
    { value: '2', viewValue: 'GTR-45 - TA Bill' },
    { value: '3', viewValue: 'GTR-40 - Grant In Bill' },
    { value: '4', viewValue: 'GTR-12 - Advance Bill' }
  ];


  billcategory_list: any[] = [
    { value: '1', viewValue: 'Regular' },
    { value: '2', viewValue: 'TC' },
    { value: '3', viewValue: 'NIL' },
    { value: '4', viewValue: 'Regular/Challan' }
  ];


  major_list: any[] = [
    { value: '1', viewValue: '3451:Secretariat-Economic Services' },
    {
      value: '2', viewValue: '5475:Capital Outlay on other General Economics Services'
    },
    { value: '3', viewValue: '2401:Crop Husbandry' },
    { value: '4', viewValue: '2071:Pensions and Other Retirement Benefits' },
    { value: '5', viewValue: '2058:Stationery and Printing' },
    { value: '6 : Secretariat-Social Services', viewValue: '2251 : Secretariat-Social Services' },
    { value: '7 : Interest Payments', viewValue: '2049 : Interest Payments' },
    { value: '8 : Water Supply and Sanitation', viewValue: '2215 : Water Supply and Sanitation' },
    { value: '9 : Ecology and Environment', viewValue: '3435 : Ecology and Environment' },
    { value: '10 : Capital Outlay on Urban Development', viewValue: '4217 : Capital Outlay on Urban Development' },
    { value: '11 : General Education', viewValue: '2202 : General Education' },
  ];

  exempted_list: any[] = [
    { value: '1', viewValue: 'Yes' },
    { value: '2', viewValue: 'No' },
  ];
  stroy = new Subject<void>();

  dataSource = new MatTableDataSource<any>(this.ELEMENT_DATA);

  private paginator: MatPaginator;
  private sort: MatSort;

  showTable: Boolean = false;
  selection = new SelectionModel<any>(true, []);


  searchListForm: FormGroup;
  ddonameCtrl: FormControl = new FormControl();

  todayDate = Date.now();

  commentGrantDetails(): void {
    const dialogRef = this.dialog.open(PartyDetailsComponent, {
      width: '500px',
    });

    dialogRef.afterClosed().subscribe(result => {
      console.log('The dialog was closed');
    });
  }


  @ViewChild(MatSort) set matSort(ms: MatSort) {
    this.sort = ms;
    this.setDataSourceAttributes();
  }

  @ViewChild(MatPaginator) set matPaginator(mp: MatPaginator) {
    this.paginator = mp;
    this.setDataSourceAttributes();
  }

  constructor(private router: Router,
    private fb: FormBuilder,
    public dialog: MatDialog,
  ) { }


  ngOnInit() {
    this.epaymentCustodyFormData();
  }

  epaymentCustodyFormData() {
    this.epaymentCustodyForm = this.fb.group({
      Billrefernum: [''],
      tokenno: [''],
      majorhead: [''],
      chequeamount: [''],
      billamount: [''],
      netamount: [''],
      partyName: [''],
      auditorname: [''],
      billcategory: [''],
      billtypes: [''],
      ddono: [''],
      cardexno: [''],
      ddoname: [''],
      billate: [''],
      Tokenno: [''],
      regBill: ['']


    });
  }

  setDataSourceAttributes() {
    this.dataSource.paginator = this.paginator;
    this.dataSource.sort = this.sort;
  }

  onclickStatus(data) {
    if (data.active) {
      data.active = false;
    } else {
      data.active = true;
    }
    return data;
  }

  clearForm() {
    this.searchListForm.reset();
  }

  search() {
    this.showTable = true;
  }

  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.dataSource.data.length;
    return numSelected === numRows;
  }

  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.dataSource.data.forEach(row => this.selection.select(row));
  }
  submitDetails() {

  }
  checkboxLabel(row?: any): string {

    if (!row) {
      return `${this.isAllSelected() ? 'select' : 'deselect'} all`;
    }
    return `${this.selection.isSelected(row) ? 'deselect' : 'select'} row ${row.position + 1}`;
  }

  goToInwardAudit() {
    this.router.navigate(['../inward/inward-physical-bill-audit-level']);
  }

}




