import { Component, OnInit, ViewChild, Inject } from '@angular/core';

import { FormControl, FormGroup, FormBuilder, Validators } from '@angular/forms';
import { MatDialog, MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { MatPaginator, MatSort, MatTableDataSource } from '@angular/material';
import { Router } from '@angular/router';
import { CommonListing } from 'src/app/model/common-listing';
import { SelectionModel } from '@angular/cdk/collections';
// import { WorkflowDetailsGrantComponent } from '../../workflow-details-grant/workflow-details-grant.component';
import { PartyDetailsComponent } from '../../party-details/party-details.component';
import { WorkflowDetailsGrantComponent } from '../../../grant/workflow-details-grant/workflow-details-grant.component';
import { ListValue } from 'src/app/model/paoModel';
import { PaoDirectives } from 'src/app/common/directive/pao';
import { SavedBill } from 'src/app/model/treasury-bill';


const ELEMENT_DATA: any[] = [
  {

    billRefNo: '368',
    tokenNo: '552',
    billRegNo: '331',
    mhead: '2054',
    ddoNo: '4',
    cardexNo: '4',
    billAmount: '10000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019',
    inwardBillDate: '25-Jan-2019',
    ddoName: '	Collector Office, Gandhinagar',
    bilCat: 'Regular',
    authiorname: '',
    billGrossAmount: '11000.00',
    partyName: 'Mr. Abc'
  }
];

@Component({
  selector: 'app-saved-bill',
  templateUrl: './saved-bill.component.html',
  styleUrls: ['./saved-bill.component.css']
})
export class SavedBillComponent implements OnInit {
  Element_Data: SavedBill[] = [
    {
      billRefNo: '368',
      tokenNo: '552',
      billRegNo: '331',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '369',
      tokenNo: '553',
      billRegNo: '332',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '370',
      tokenNo: '554',
      billRegNo: '333',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '371',
      tokenNo: '555',
      billRegNo: '334',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '372',
      tokenNo: '556',
      billRegNo: '335',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '373',
      tokenNo: '557',
      billRegNo: '336',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '374',
      tokenNo: '558',
      billRegNo: '337',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '375',
      tokenNo: '559',
      billRegNo: '338',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '376',
      tokenNo: '560',
      billRegNo: '339',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '377',
      tokenNo: '561',
      billRegNo: '340',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '378',
      tokenNo: '562',
      billRegNo: '341',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '379',
      tokenNo: '563',
      billRegNo: '342',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '380',
      tokenNo: '564',
      billRegNo: '343',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '381',
      tokenNo: '565',
      billRegNo: '344',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '382',
      tokenNo: '566',
      billRegNo: '345',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '383',
      tokenNo: '567',
      billRegNo: '346',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '384',
      tokenNo: '568',
      billRegNo: '347',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '385',
      tokenNo: '569',
      billRegNo: '348',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '386',
      tokenNo: '570',
      billRegNo: '349',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '387',
      tokenNo: '571',
      billRegNo: '350',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '388',
      tokenNo: '572',
      billRegNo: '351',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '389',
      tokenNo: '573',
      billRegNo: '352',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '390',
      tokenNo: '574',
      billRegNo: '353',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '391',
      tokenNo: '575',
      billRegNo: '354',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '392',
      tokenNo: '576',
      billRegNo: '355',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '393',
      tokenNo: '577',
      billRegNo: '356',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '394',
      tokenNo: '578',
      billRegNo: '357',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '395',
      tokenNo: '579',
      billRegNo: '358',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '396',
      tokenNo: '580',
      billRegNo: '359',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '397',
      tokenNo: '581',
      billRegNo: '360',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '398',
      tokenNo: '582',
      billRegNo: '361',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '399',
      tokenNo: '583',
      billRegNo: '362',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '400',
      tokenNo: '584',
      billRegNo: '363',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '401',
      tokenNo: '585',
      billRegNo: '364',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '402',
      tokenNo: '586',
      billRegNo: '365',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '403',
      tokenNo: '587',
      billRegNo: '366',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '404',
      tokenNo: '588',
      billRegNo: '367',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '405',
      tokenNo: '589',
      billRegNo: '368',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '406',
      tokenNo: '590',
      billRegNo: '369',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '407',
      tokenNo: '591',
      billRegNo: '370',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '408',
      tokenNo: '592',
      billRegNo: '371',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '409',
      tokenNo: '593',
      billRegNo: '372',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '410',
      tokenNo: '594',
      billRegNo: '373',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '411',
      tokenNo: '595',
      billRegNo: '374',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '412',
      tokenNo: '596',
      billRegNo: '375',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '413',
      tokenNo: '597',
      billRegNo: '376',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '414',
      tokenNo: '598',
      billRegNo: '377',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '415',
      tokenNo: '599',
      billRegNo: '378',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '416',
      tokenNo: '600',
      billRegNo: '379',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '417',
      tokenNo: '601',
      billRegNo: '380',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '418',
      tokenNo: '602',
      billRegNo: '381',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '419',
      tokenNo: '603',
      billRegNo: '382',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '420',
      tokenNo: '604',
      billRegNo: '383',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '421',
      tokenNo: '605',
      billRegNo: '384',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '422',
      tokenNo: '606',
      billRegNo: '385',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '423',
      tokenNo: '607',
      billRegNo: '386',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '424',
      tokenNo: '608',
      billRegNo: '387',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '425',
      tokenNo: '609',
      billRegNo: '388',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '426',
      tokenNo: '610',
      billRegNo: '389',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '427',
      tokenNo: '611',
      billRegNo: '390',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '428',
      tokenNo: '612',
      billRegNo: '391',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '429',
      tokenNo: '613',
      billRegNo: '392',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '430',
      tokenNo: '614',
      billRegNo: '393',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '431',
      tokenNo: '615',
      billRegNo: '394',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '432',
      tokenNo: '616',
      billRegNo: '395',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '433',
      tokenNo: '617',
      billRegNo: '396',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '434',
      tokenNo: '618',
      billRegNo: '397',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '435',
      tokenNo: '619',
      billRegNo: '398',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '436',
      tokenNo: '620',
      billRegNo: '399',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '437',
      tokenNo: '621',
      billRegNo: '400',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '438',
      tokenNo: '622',
      billRegNo: '401',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '439',
      tokenNo: '623',
      billRegNo: '402',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '440',
      tokenNo: '624',
      billRegNo: '403',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '441',
      tokenNo: '625',
      billRegNo: '404',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '442',
      tokenNo: '626',
      billRegNo: '405',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '443',
      tokenNo: '627',
      billRegNo: '406',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '444',
      tokenNo: '628',
      billRegNo: '407',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '445',
      tokenNo: '629',
      billRegNo: '408',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '446',
      tokenNo: '630',
      billRegNo: '409',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '447',
      tokenNo: '631',
      billRegNo: '410',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '448',
      tokenNo: '632',
      billRegNo: '411',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '449',
      tokenNo: '633',
      billRegNo: '412',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '450',
      tokenNo: '634',
      billRegNo: '413',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '451',
      tokenNo: '635',
      billRegNo: '414',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '452',
      tokenNo: '636',
      billRegNo: '415',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '453',
      tokenNo: '637',
      billRegNo: '416',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '454',
      tokenNo: '638',
      billRegNo: '417',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '455',
      tokenNo: '639',
      billRegNo: '418',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '456',
      tokenNo: '640',
      billRegNo: '419',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '457',
      tokenNo: '641',
      billRegNo: '420',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '458',
      tokenNo: '642',
      billRegNo: '421',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '459',
      tokenNo: '643',
      billRegNo: '422',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '460',
      tokenNo: '644',
      billRegNo: '423',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '461',
      tokenNo: '645',
      billRegNo: '424',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '462',
      tokenNo: '646',
      billRegNo: '425',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '463',
      tokenNo: '647',
      billRegNo: '426',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '464',
      tokenNo: '648',
      billRegNo: '427',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '465',
      tokenNo: '649',
      billRegNo: '428',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '466',
      tokenNo: '650',
      billRegNo: '429',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '467',
      tokenNo: '651',
      billRegNo: '430',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '468',
      tokenNo: '652',
      billRegNo: '431',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '469',
      tokenNo: '653',
      billRegNo: '432',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '470',
      tokenNo: '654',
      billRegNo: '433',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '471',
      tokenNo: '655',
      billRegNo: '434',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '472',
      tokenNo: '656',
      billRegNo: '435',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '473',
      tokenNo: '657',
      billRegNo: '436',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '474',
      tokenNo: '658',
      billRegNo: '437',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '475',
      tokenNo: '659',
      billRegNo: '438',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '476',
      tokenNo: '660',
      billRegNo: '439',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '477',
      tokenNo: '661',
      billRegNo: '440',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '478',
      tokenNo: '662',
      billRegNo: '441',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '479',
      tokenNo: '663',
      billRegNo: '442',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '480',
      tokenNo: '664',
      billRegNo: '443',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '481',
      tokenNo: '665',
      billRegNo: '444',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '482',
      tokenNo: '666',
      billRegNo: '445',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '483',
      tokenNo: '667',
      billRegNo: '446',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '484',
      tokenNo: '668',
      billRegNo: '447',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '485',
      tokenNo: '669',
      billRegNo: '448',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '486',
      tokenNo: '670',
      billRegNo: '449',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '487',
      tokenNo: '671',
      billRegNo: '450',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '488',
      tokenNo: '672',
      billRegNo: '451',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '489',
      tokenNo: '673',
      billRegNo: '452',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '490',
      tokenNo: '674',
      billRegNo: '453',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '491',
      tokenNo: '675',
      billRegNo: '454',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '492',
      tokenNo: '676',
      billRegNo: '455',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '493',
      tokenNo: '677',
      billRegNo: '456',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '494',
      tokenNo: '678',
      billRegNo: '457',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '495',
      tokenNo: '679',
      billRegNo: '458',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '496',
      tokenNo: '680',
      billRegNo: '459',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '497',
      tokenNo: '681',
      billRegNo: '460',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '498',
      tokenNo: '682',
      billRegNo: '461',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '499',
      tokenNo: '683',
      billRegNo: '462',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '500',
      tokenNo: '684',
      billRegNo: '463',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '501',
      tokenNo: '685',
      billRegNo: '464',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '502',
      tokenNo: '686',
      billRegNo: '465',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '503',
      tokenNo: '687',
      billRegNo: '466',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '504',
      tokenNo: '688',
      billRegNo: '467',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '505',
      tokenNo: '689',
      billRegNo: '468',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '506',
      tokenNo: '690',
      billRegNo: '469',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '507',
      tokenNo: '691',
      billRegNo: '470',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '508',
      tokenNo: '692',
      billRegNo: '471',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '509',
      tokenNo: '693',
      billRegNo: '472',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '510',
      tokenNo: '694',
      billRegNo: '473',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '511',
      tokenNo: '695',
      billRegNo: '474',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '512',
      tokenNo: '696',
      billRegNo: '475',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '513',
      tokenNo: '697',
      billRegNo: '476',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '514',
      tokenNo: '698',
      billRegNo: '477',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '515',
      tokenNo: '699',
      billRegNo: '478',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '516',
      tokenNo: '700',
      billRegNo: '479',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },
    {
      billRefNo: '517',
      tokenNo: '701',
      billRegNo: '480',
      mhead: '2054',
      ddoNo: '4',
      cardexNo: '4',
      billAmount: '10000.00',
      billType: 'Pay Bill',
      billDate: '25-Feb-2019 12:00 AM',
      inwardBillDate: '25-Jan-2019 11:00 AM',
      ddoName: '	Collector Office, Gandhinagar',
      bilCat: 'Regular',
      billGrossAmount: '11000.00',
      partyName: 'Mr. Abc',
      approverName: 'Mr.Pratik Ramlal Shah'
    },

  ];

  // Form Group
  savedOnlineBillForm: FormGroup;
  // Variable
  isSearch: Boolean = true;
  AddShow: Boolean = false;
  valueRequired: Boolean = false;
  // table source
  newdisplayedColumns: string[] = ['select', 'billRefNo', 'billRegNo',
    'tokenNo', 'billDate', 'inwardBillDate', 'ddoNo', 'cardexNo', 'ddoName',
    'billType', 'mhead', 'bilCat', 'billGrossAmount', 'billAmount', 'partyName', 'approverName', 'action'];
  newdataSource = new MatTableDataSource<any>(this.Element_Data);
  selection = new SelectionModel<any>(true, []);
  // Form Control
  forwardtypeCtrl: FormControl = new FormControl();
  majorheadeCtrl: FormControl = new FormControl();
  billTypeeCtrl: FormControl = new FormControl();
  ddoNameCtrl: FormControl = new FormControl();
  auditornameCtrl: FormControl = new FormControl();
  billCategoryCtrl: FormControl = new FormControl();


  // Lists

  auditor_list: ListValue[] = [{
    value: '1',
    viewValue: 'Shri. Pratik Shah'
  },

  ];

  ddoName_list: ListValue[] = [
    { value: '1', viewValue: '	Collector Office, Gandhinagar' },
  ];

  major_list: ListValue[] = [
    { value: '1', viewValue: '3451:Secretariat-Economic Services' },
    {
      value: '2', viewValue: '5475:Capital Outlay on other General Economics Services'
    },
    { value: '3', viewValue: '2401:Crop Husbandry' },
    { value: '4', viewValue: '2071:Pensions and Other Retirement Benefits' },
    { value: '5', viewValue: '2058:Stationery and Printing' },
    { value: '6 : Secretariat-Social Services', viewValue: '2251 : Secretariat-Social Services' },
    { value: '7 : Interest Payments', viewValue: '2049 : Interest Payments' },
    { value: '8 : Water Supply and Sanitation', viewValue: '2215 : Water Supply and Sanitation' },
    { value: '9 : Ecology and Environment', viewValue: '3435 : Ecology and Environment' },
    { value: '10 : Capital Outlay on Urban Development', viewValue: '4217 : Capital Outlay on Urban Development' },
    { value: '11 : General Education', viewValue: '2202 : General Education' },
  ];


  billCategory_list: ListValue[] = [
    { value: '1', viewValue: 'Regular' },
    { value: '2', viewValue: 'TC' },
    { value: '3', viewValue: 'NIL' },
    { value: '4', viewValue: 'Regular/Challan' }
  ];

  billType_list: ListValue[] = [
    { value: '1', viewValue: 'GTR-30 - Pay Bill' },
    { value: '2', viewValue: 'GTR-45 - TA Bill' },
    { value: '3', viewValue: 'GTR-40 - Grant In Bill' },
    { value: '4', viewValue: 'GTR-12 - Advance Bill' }
  ];

  forward_list: ListValue[] = [
    { value: '1', viewValue: 'Authority' },
  ];
  @ViewChild(MatPaginator) paginator: MatPaginator;
  constructor(private router: Router, public dialog: MatDialog, private fb: FormBuilder,) { }
  directiveObject = new PaoDirectives(this.router, this.dialog);

  ngOnInit() {
    this.newdataSource.paginator = this.paginator;
    this.savedOnlineBillFormData();
  }
  gotopage() {
    this.router.navigate(['/pao/saved-bill/bill-prepration-fom']);
  }

  // navigation
  goToDashboard() {
    this.router.navigate(['/pao/inward-bill']);
  }
  savedOnlineBillFormData() {
    this.savedOnlineBillForm = this.fb.group({
      BillRefNo: [''],
      Tokenno: [''],
      majorhead: [''],
      billType: [''],
      Billtype: [''],
      cardexNo: [''],
      ddoName: [''],
      billate: [''],
      netamount: [''],
      auditorname: [''],
      billCategory: [''],
      forwardautho: [''],
      billRegNo: [''],
      auditorctrl: ['1'],
      ddoNo: [''],
      grossamount: [''],
      inardbillDate: [''],
      BillFromDate: ['']
    });
  }

  search() {
    this.isSearch = false;
  }

  isAllSelected() {
    if (this.selection.selected.length === 1) {
      this.AddShow = true;
    } else if (this.selection.selected.length === 2) {
      this.AddShow = true;
    } else if (this.selection.selected.length === 0) {
      this.AddShow = false;
    } else {
      this.AddShow = false;
    }
    const numSelected = this.selection.selected.length;
    const numRows = this.newdataSource.data.length;
    return numSelected === numRows;
  }
  masterToggle() {
    if (this.selection.selected.length === 1) {
      this.AddShow = true;
    } else if (this.selection.selected.length === 2) {
      this.AddShow = true;
    } else if (this.selection.selected.length === 0) {
      this.AddShow = false;
    } else {
      this.AddShow = false;
    }
    this.isAllSelected() ?
      this.selection.clear() :
      this.newdataSource.data.forEach(row => this.selection.select(row));
  }
  FromDate(event) {
    const fromdate = this.savedOnlineBillForm.get('BillFromDate').value;
    if (fromdate != '') {
      this.valueRequired = true;
    }
  }
  checkboxLabel(row?: any): string {
    if (!row) {
      return `${this.isAllSelected() ? 'select' : 'deselect'} all`;
    }
    return `${this.selection.isSelected(row) ? 'deselect' : 'select'} row ${row.position + 1}`;
  }
}
