import { Component, OnInit, ViewChild, Inject } from '@angular/core';
import { FormControl, FormGroup, FormBuilder, Validators } from '@angular/forms';
import { MatDialog, MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { MatPaginator, MatSort, MatTableDataSource } from '@angular/material';
import { Router } from '@angular/router';
import { CommonListing } from 'src/app/model/common-listing';
import { SelectionModel } from '@angular/cdk/collections';
import { ListValue } from 'src/app/model/paoModel';
import { PaoDirectives } from 'src/app/common/directive/pao';
import { ApproveReject } from 'src/app/model/treasury-bill';




@Component({
  selector: 'app-audit-bills-approved-reject',
  templateUrl: './audit-bills-approved-reject.component.html',
  styleUrls: ['./audit-bills-approved-reject.component.css']
})
export class AuditBillsApprovedRejectComponent implements OnInit {

  ELEMENT_DATA: ApproveReject[] = [{

    billRefNo: '368',
    tokenNo: '552',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '331',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '369',
    tokenNo: '553',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	332',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '370',
    tokenNo: '554',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	333',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '371',
    tokenNo: '555',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	334',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '372',
    tokenNo: '556',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	335',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '373',
    tokenNo: '557',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	336',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '374',
    tokenNo: '558',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	337',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '375',
    tokenNo: '559',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	338',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '376',
    tokenNo: '560',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	339',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '377',
    tokenNo: '561',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	340',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '378',
    tokenNo: '562',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	341',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '379',
    tokenNo: '563',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	342',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '380',
    tokenNo: '564',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	343',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '381',
    tokenNo: '565',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	344',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '382',
    tokenNo: '566',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	345',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '383',
    tokenNo: '567',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	346',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '384',
    tokenNo: '568',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	347',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '385',
    tokenNo: '569',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	348',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '386',
    tokenNo: '570',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	349',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '387',
    tokenNo: '571',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	350',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '388',
    tokenNo: '572',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	351',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '389',
    tokenNo: '573',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	352',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '390',
    tokenNo: '574',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	353',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '391',
    tokenNo: '575',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	354',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '392',
    tokenNo: '576',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	355',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '393',
    tokenNo: '577',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	356',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '394',
    tokenNo: '578',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	357',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '395',
    tokenNo: '579',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	358',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '396',
    tokenNo: '580',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	359',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '397',
    tokenNo: '581',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	360',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '398',
    tokenNo: '582',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	361',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '399',
    tokenNo: '583',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	362',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '400',
    tokenNo: '584',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	363',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '401',
    tokenNo: '585',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	364',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '402',
    tokenNo: '586',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	365',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '403',
    tokenNo: '587',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	366',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '404',
    tokenNo: '588',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	367',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '405',
    tokenNo: '589',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	368',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '406',
    tokenNo: '590',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	369',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '407',
    tokenNo: '591',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	370',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '408',
    tokenNo: '592',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	371',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '409',
    tokenNo: '593',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	372',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '410',
    tokenNo: '594',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	373',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '411',
    tokenNo: '595',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	374',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '412',
    tokenNo: '596',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	375',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '413',
    tokenNo: '597',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	376',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '414',
    tokenNo: '598',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	377',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '415',
    tokenNo: '599',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	378',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '416',
    tokenNo: '600',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	379',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '417',
    tokenNo: '601',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	380',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '418',
    tokenNo: '602',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	381',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '419',
    tokenNo: '603',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	382',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '420',
    tokenNo: '604',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	383',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '421',
    tokenNo: '605',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	384',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '422',
    tokenNo: '606',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	385',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '423',
    tokenNo: '607',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	386',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '424',
    tokenNo: '608',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	387',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '425',
    tokenNo: '609',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	388',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '426',
    tokenNo: '610',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	389',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '427',
    tokenNo: '611',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	390',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '428',
    tokenNo: '612',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	391',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '429',
    tokenNo: '613',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	392',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '430',
    tokenNo: '614',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	393',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '431',
    tokenNo: '615',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	394',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '432',
    tokenNo: '616',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	395',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '433',
    tokenNo: '617',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	396',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '434',
    tokenNo: '618',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	397',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '435',
    tokenNo: '619',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	398',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '436',
    tokenNo: '620',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	399',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '437',
    tokenNo: '621',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	400',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '438',
    tokenNo: '622',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	401',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '439',
    tokenNo: '623',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	402',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '440',
    tokenNo: '624',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	403',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '441',
    tokenNo: '625',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	404',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '442',
    tokenNo: '626',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	405',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '443',
    tokenNo: '627',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	406',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '444',
    tokenNo: '628',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	407',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '445',
    tokenNo: '629',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	408',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '446',
    tokenNo: '630',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	409',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '447',
    tokenNo: '631',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	410',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '448',
    tokenNo: '632',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	411',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '449',
    tokenNo: '633',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	412',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '450',
    tokenNo: '634',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	413',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '451',
    tokenNo: '635',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	414',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '452',
    tokenNo: '636',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	415',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '453',
    tokenNo: '637',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	416',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '454',
    tokenNo: '638',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	417',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '455',
    tokenNo: '639',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	418',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '456',
    tokenNo: '640',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	419',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '457',
    tokenNo: '641',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	420',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '458',
    tokenNo: '642',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	421',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '459',
    tokenNo: '643',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	422',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '460',
    tokenNo: '644',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	423',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '461',
    tokenNo: '645',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	424',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '462',
    tokenNo: '646',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	425',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '463',
    tokenNo: '647',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	426',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '464',
    tokenNo: '648',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	427',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '465',
    tokenNo: '649',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	428',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '466',
    tokenNo: '650',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	429',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '467',
    tokenNo: '651',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	430',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '468',
    tokenNo: '652',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	431',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '469',
    tokenNo: '653',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	432',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '470',
    tokenNo: '654',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	433',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '471',
    tokenNo: '655',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	434',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '472',
    tokenNo: '656',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	435',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '473',
    tokenNo: '657',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	436',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '474',
    tokenNo: '658',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	437',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '475',
    tokenNo: '659',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	438',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '476',
    tokenNo: '660',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	439',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '477',
    tokenNo: '661',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	440',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '478',
    tokenNo: '662',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	441',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '479',
    tokenNo: '663',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	442',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '480',
    tokenNo: '664',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	443',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '481',
    tokenNo: '665',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	444',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '482',
    tokenNo: '666',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	445',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '483',
    tokenNo: '667',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	446',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '484',
    tokenNo: '668',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	447',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '485',
    tokenNo: '669',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	448',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '486',
    tokenNo: '670',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	449',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '487',
    tokenNo: '671',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	450',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '488',
    tokenNo: '672',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	451',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '489',
    tokenNo: '673',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	452',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '490',
    tokenNo: '674',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	453',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '491',
    tokenNo: '675',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	454',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '492',
    tokenNo: '676',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	455',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '493',
    tokenNo: '677',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	456',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '494',
    tokenNo: '678',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	457',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '495',
    tokenNo: '679',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	458',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '496',
    tokenNo: '680',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	459',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '497',
    tokenNo: '681',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	460',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '498',
    tokenNo: '682',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	461',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '499',
    tokenNo: '683',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	462',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '500',
    tokenNo: '684',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	463',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '501',
    tokenNo: '685',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	464',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '502',
    tokenNo: '686',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	465',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '503',
    tokenNo: '687',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	466',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '504',
    tokenNo: '688',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	467',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '505',
    tokenNo: '689',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	468',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '506',
    tokenNo: '690',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	469',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '507',
    tokenNo: '691',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	470',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '508',
    tokenNo: '692',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	471',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '509',
    tokenNo: '693',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	472',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '510',
    tokenNo: '694',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	473',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '511',
    tokenNo: '695',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	474',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '512',
    tokenNo: '696',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	475',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '513',
    tokenNo: '697',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	476',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '514',
    tokenNo: '698',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	477',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '515',
    tokenNo: '699',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	478',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '516',
    tokenNo: '700',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	479',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  {

    billRefNo: '517',
    tokenNo: '701',
    mhead: '2054',
    cardexNo: '4',
    billRegNo: '	480',
    billAmount: '10000.00',
    billGrossAmount: '11000.00',
    billType: 'Pay Bill',
    billDate: '25-Feb-2019 11:00 AM',
    ddoName: '  Collector Office, Gandhinagar',
    billCat: 'Regular',
    authiorName: 'Shri Pratik K Shah',
    district: 'Gandhinagar',
    ddoNo: '4',
    partyName: 'Mr. Abc',
    approverName: 'Mr. Praik Ramlal Shah',
    vitocode: '152',
    inwardDate: '25-feb-2019 10:00 AM',
    status: 'Pass'
  },
  ];


  // Date
  todayDate = new Date();
  // Form Group
  auditApproveRejectForm: FormGroup;
  // Form Control
  ddoNameCtrl: FormControl = new FormControl();
  auditornameCtrl: FormControl = new FormControl();
  billTypeCtrl: FormControl = new FormControl();
  majorheadCtrl: FormControl = new FormControl();
  // Variable
  isSearch: Boolean = true;
  valueRequired: Boolean = false;
  // Table Source
  newdisplayedColumns: string[] = ['select', 'billRefNo', 'billRegNo', 'tokenNo',
    'billDate', 'inwardDate', 'ddoNo', 'cardexNo', 'ddoName', 'billType', 'mhead',
    'billCat', 'billGrossAmount', 'billAmount', 'partyName', 'approverName', 'status', 'action'];
  newdataSource = new MatTableDataSource<any>(this.ELEMENT_DATA);

  selection = new SelectionModel<any>(true, []);
  // Lists
  auditor_list: ListValue[] = [{
    value: '1',
    viewValue: 'Shri. Pratik Shah'
  },

  ];


  major_list: ListValue[] = [
    { value: '1', viewValue: '3451:Secretariat-Economic Services' },
    {
      value: '2', viewValue: '5475:Capital Outlay on other General Economics Services'
    },
    { value: '3', viewValue: '2401:Crop Husbandry' },
    { value: '4', viewValue: '2071:Pensions and Other Retirement Benefits' },
    { value: '5', viewValue: '2058:Stationery and Printing' },
    { value: '6 : Secretariat-Social Services', viewValue: '2251 : Secretariat-Social Services' },
    { value: '7 : Interest Payments', viewValue: '2049 : Interest Payments' },
    { value: '8 : Water Supply and Sanitation', viewValue: '2215 : Water Supply and Sanitation' },
    { value: '9 : Ecology and Environment', viewValue: '3435 : Ecology and Environment' },
    { value: '10 : Capital Outlay on Urban Development', viewValue: '4217 : Capital Outlay on Urban Development' },
    { value: '11 : General Education', viewValue: '2202 : General Education' },
  ];
  ddoName_list: ListValue[] = [
    { value: '1', viewValue: '	Collector Office, Gandhinagar' },
  ];


  billCategory_list: ListValue[] = [{
    value: '1',
    viewValue: 'Regular'
  },
  {
    value: '2',
    viewValue: 'TC'
  },
  {
    value: '3',
    viewValue: 'NIL'
  },
  {
    value: '4',
    viewValue: 'Regular/Challan'
  }
  ];
  billType_list: ListValue[] = [
    { value: '1', viewValue: 'GTR-30 - Pay Bill' },
    { value: '2', viewValue: 'GTR-45 - TA Bill' },
    { value: '3', viewValue: 'GTR-40 - Grant In Bill' },
    { value: '4', viewValue: 'GTR-12 - Advance Bill' }
  ];



  @ViewChild(MatPaginator) paginator: MatPaginator;
  constructor(private router: Router, public dialog: MatDialog, private fb: FormBuilder,) { }
  directiveObject = new PaoDirectives(this.router, this.dialog);
  ngOnInit() {
    this.newdataSource.paginator = this.paginator;
    this.auditApproveRejectFormData();
  }

  auditApproveRejectFormData() {
    this.auditApproveRejectForm = this.fb.group({
      BillRefNo: [''],
      billType: [''],
      Tokenno: [''],
      majorhead: [''],
      Billtype: [''],
      cardexNo: [''],
      ddoName: [''],
      billate: [''],
      district: [''],
      netamount: [''],
      auditorname: [''],
      billCategory: [''],
      billRegNo: [''],
      auditorctrl: ['1'],
      Grossamount: [''],
      BillFromDate: [''],
      regNo: ['']
    });
  }
  FromDate(event) {
    const fromdate = this.auditApproveRejectForm.get('BillFromDate').value;
    if (fromdate != '') {
      this.valueRequired = true;
    }
  }

  search() {
    this.isSearch = false;
  }

  gotopage() {
    this.router.navigate(['/pao/saved-bill/bill-prepration-fom']);
  }
}
